- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
         name: 66025010-nextjs-container #docker container name
         image: 66025010-nextjs:latest #docker image name
         ports:
           - "3000:1609"
         state: started
         restart: true
